proj_django/app_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
urlpatterns = [
    url(r'index$',views.index, name ='index'),
    url(r'salvar_form$',views.salvar_form, name ='salvar_form'),
    url(r'insereposicao$',views.insereposicao, name ='insereposicao'),
    url(r'insereposicao2$',views.insereposicao2, name ='insereposicao2'),
    url(r'rota$',views.my_custom_sql, name ='rota'),
]

proj_django/proj_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('app_django.urls')),
]

proj_django/app_django/models.py
from django.contrib.gis.db import models

# Create your models here.
class Usuarios(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField('Qual o seu nome?', max_length=30)
    dest = models.CharField('Qual seu destino?',max_length=100)

    class Meta:
        db_table='usuarios'
        managed=True
class Posicao(models.Model):
    id = models.AutoField(primary_key=True)
    id_usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    geom = models.PointField()
    data_criacao = models.DateField(auto_now_add=True)
    descricao = models.CharField('Descreva a barreira:', max_length=100)
    class Meta:
        db_table='posicao'
        managed=True

class Posicao_atual(models.Model):
    id = models.AutoField(primary_key=True)
    id_usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    geom = models.PointField()
    class Meta:
        db_table='posicao_atual'
        managed=True

proj_django/app_django/forms.py
from django import forms
from . models import Usuarios, Posicao


class Form_usuarios(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ['nome','dest']

class Form_desc(forms.ModelForm):
    class Meta:
        model = Posicao
        fields = ['descricao']

proj_django/app_django/views.py
from django.shortcuts import render
from . forms import Form_usuarios, Form_desc
from django.http import JsonResponse
import json
from . models import Posicao, Usuarios, Posicao_atual
from django.contrib.gis.geos import Point
from django.db import connection
import googlemaps

gmaps = googlemaps.Client(key='#########')
def SelecionaInicio():
    with connection.cursor() as cursor:
        cursor.execute("SELECT osm_id FROM ways_vertices_pgr, posicao_user ORDER BY ST_Distance(ways_vertices_pgr.the_geom, posicao_user.geom ) limit 1")
        row = cursor.fetchall()
        pontoI = row[0]
        return pontoI

def SelecionaFim():
    with connection.cursor() as cursor:
        cursor.execute("SELECT dest from usuarios")
        row = cursor.fetchall()
    #user_dest = Usuarios.objects.get(dest=dest)
    user_dest = row[-1]
    result = gmaps.geocode(user_dest)
    pontoFim = str(result[0]['geometry']['location']['lng']) + ',' + str(result[0]['geometry']['location']['lat'])
    with connection.cursor() as cursor:
        cursor.execute("create or replace view destino as SELECT * FROM ways_vertices_pgr ORDER BY ST_Distance(ways_vertices_pgr.the_geom, ST_SetSRID(ST_Point(%s), 4326)) limit 1"%pontoFim)
        cursor.execute("SELECT osm_id FROM ways_vertices_pgr ORDER BY ST_Distance(ways_vertices_pgr.the_geom, ST_SetSRID(ST_Point(%s), 4326)) limit 1"%pontoFim)
        row = cursor.fetchall()
        pontoF = row[0]
        return pontoF




def my_custom_sql():
    #ponto1 = SelecionaInicio()
    ponto1 = [9597873291]
    ponto2 = SelecionaFim()
    with connection.cursor() as cursor:
        #cursor.execute("CREATE OR REPLACE VIEW rota as SELECT the_geom, dataid, waysfinal.source_osm, target_osm, waysfinal.custo FROM waysfinal JOIN(SELECT * FROM pgr_dijkstra('SELECT dataid as id, source_osm AS source, target_osm AS target, custo AS cost FROM waysfinal',%s, %s , directed => false)) AS route ON waysfinal.gid = route.edge"%(ponto1[0],ponto2[0]))
        cursor.execute("CREATE OR REPLACE VIEW rota AS SELECT the_geom, gid, waysfinal.source_osm, target_osm FROM waysfinal JOIN (SELECT * FROM pgr_dijkstra('SELECT gid as id, source_osm AS source, target_osm AS target, custo AS cost FROM waysfinal',%s, %s,directed => false)) AS route ON waysfinal.gid = route.edge"%(ponto1[0],ponto2[0]))

def index(request):
    form = Form_usuarios()
    return render(request,'index.html',{'form':form})

def salvar_form(request):
    if request.method=='POST':
        form = Form_usuarios(request.POST)
        if form.is_valid():
            result = form.save()
            id = result.id
            b=my_custom_sql()
            return render(request,'mapa.html',{'id':id})

def insereposicao(request):
    if request.is_ajax():
        if request.method =='POST':
            dicionario = dict(request.POST)
            id_usuario = dicionario['id'][0]
            descri = dicionario['desc'][0]


            ponto = Point(float(dicionario['ponto[]'][0]),float(dicionario['ponto[]'][1]))
            obj_usuario = Usuarios.objects.get(id=id_usuario)
            #descri =Form_desc(request.POST)
            obj = Posicao(id_usuarios=obj_usuario, geom=ponto,descricao=descri)
            obj.save()


            resposta = '{result:ok}'
            return JsonResponse(json.dumps(resposta),safe=False)


def insereposicao2(request):
    if request.is_ajax():
        if request.method =='POST':
            dicionario = dict(request.POST)
            id_usuario = dicionario['id'][0]

            ponto = Point(float(dicionario['ponto[]'][0]),float(dicionario['ponto[]'][1]))
            obj_usuario = Usuarios.objects.get(id=id_usuario)
            obj = Posicao_atual(id_usuarios=obj_usuario, geom=ponto)
            obj.save()


            resposta = '{result:ok}'
            #b=my_custom_sql()
            return JsonResponse(json.dumps(resposta),safe=False)

proj_django/app_django/templates/index.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Login Now">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Hórus Map</title>
    {% load static %}
    <link rel="stylesheet" href={% static "css/nicepage.css" %}>
    <link rel="stylesheet" href={% static "css/Home-3.css" %}>
    <script class="u-script" type="text/javascript" src="jquery-1.9.1.min.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.9.1, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Gruppo:400|NTR:400">


    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#5710b3">
    <meta property="og:title" content="Home 3">
    <meta property="og:type" content="website">
  </head>
  <body data-home-page="https://website1813662.nicepage.io/Home-3.html?version=847f3bd6-041d-43ca-b952-6076f4ef4250" data-home-page-title="Home 3" class="u-body u-xl-mode"><header class="u-clearfix u-custom-color-1 u-header u-header" id="sec-0e5e"><div class="u-clearfix u-sheet u-sheet-1"></div></header>
    <section class="u-align-center u-clearfix u-custom-color-1 u-section-1" id="sec-ff23">
      <img class="u-expanded-width u-image u-image-1" data-image-width="1280" data-image-height="503">
      <div class="u-container-style u-group u-radius-50 u-shape-round u-white u-group-1">
        <div class="u-container-layout u-container-layout-1"><span class="u-border-8 u-border-white u-icon u-icon-circle u-spacing-0 u-icon-1"></span>
          <h2 class="u-align-center u-custom-font u-text u-text-custom-color-1 u-text-default u-text-1">HÓRUS MAP</h2>
          <div class="u-image u-image-circle u-preserve-proportions u-image-2" alt="" data-image-width="400" data-image-height="400"></div>
          <div class="u-form u-login-control u-form-1">
            <form action="salvar_form" method="POST" class="u-clearfix u-form-custom-backend u-form-spacing-10 u-form-vertical u-inner-form" source="custom" name="form" style="padding: 50px;">
              {% csrf_token %}
              <div class="u-form-group u-form-name u-label-top">
                <label for="id_nome" class="u-custom-font u-label u-text-font u-text-grey-30 u-label-1">Usuário *</label>
                <input type="text" placeholder="Entre com seu nome" id="id_nome" name="nome" class="u-border-10 u-border-grey-10 u-grey-10 u-input u-input-rectangle u-radius-50 u-input-1" required="required" value="{{Form_usuarios}}">
              </div>
              <div class="u-form-group u-form-password u-label-top">
                <label for="id_dest" class="u-custom-font u-label u-text-font u-text-grey-30 u-label-2">Destino *</label>
                <input type="text" placeholder="Entre com seu destino" id="id_dest" name="dest" class="u-border-10 u-border-grey-10 u-grey-10 u-input u-input-rectangle u-radius-50 u-input-2" required="required" value="{{Form_usuarios}}">
              </div>
              <div class="u-align-right u-form-group u-form-submit u-label-top">
                <input type="submit" value="ENVIAR" class="u-active-palette-1-base u-border-none u-btn u-btn-round u-btn-submit u-button-style u-custom-color-1 u-hover-palette-1-base u-radius-50 u-btn-1">

              </div>
              <input type="hidden" value="" name="recaptchaResponse">
              <input type="hidden" id="siteId" name="siteId" value="1813662">
              <input type="hidden" id="pageId" name="pageId" value="1813777">
            </form>
          </div>
        </div>
      </div>
    </section>










    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-1bcc"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-align-right u-custom-font u-small-text u-text u-text-variant u-text-1">DESENVOLVIDO POR DIONATA KLAIVER</p>
      </div></footer>
  </body>
</html>

proj_django/app_django/templates/mapa.html
<!DOCTYPE html>{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>Mapa</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/css/ol.css">



    <link rel="stylesheet" href={% static "css/map.css" %} >
  </head>
  <body>
    <div id='map'>
    </div>

  <script type="text/javascript">
  const token = '{{csrf_token}}'

  var id_usuario = {{id}}

  </script>
  <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/build/ol.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script type="text/javascript" src={% static "js/map.js" %}>
  </script>
  </body>
</html>